export interface addPoliceInterface{
  apPoliceId : string,
  apFirstName : string,
  apLastName : string,
  apFatherName : string,
  apMotherName : string,
  apGender : string,
  apDoB : string,
  apDepartmentId : string,
  apDepartmentType : string,
  apDistrictName : string,
  apThanaName : string,
  apBatch : string,
  apRank : string,
  apPlacementDate : string,
  apWeaponSerial : string,
  apPresentAddress : string,
  apPermanentAddress : string,
  apEmail : string,
  apOfficePhone : string,
  apPersonalPhone : string,
  apUserName : string,
  apPassword : string,
  apConfirmPassword : string
}

